(function() {var implementors = {};
implementors["rustc_demangle"] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='rustc_demangle/struct.Demangle.html' title='rustc_demangle::Demangle'>Demangle</a>&lt;'a&gt;",];implementors["libc"] = [];implementors["backtrace"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='trait' href='backtrace/trait.Frame.html' title='backtrace::Frame'>Frame</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='trait' href='backtrace/trait.Symbol.html' title='backtrace::Symbol'>Symbol</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='backtrace/struct.SymbolName.html' title='backtrace::SymbolName'>SymbolName</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='backtrace/struct.Backtrace.html' title='backtrace::Backtrace'>Backtrace</a>",];implementors["error_chain"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='trait' href='backtrace/backtrace/trait.Frame.html' title='backtrace::backtrace::Frame'>Frame</a> + 'static","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='trait' href='backtrace/symbolize/trait.Symbol.html' title='backtrace::symbolize::Symbol'>Symbol</a> + 'static","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='backtrace/symbolize/struct.SymbolName.html' title='backtrace::symbolize::SymbolName'>SymbolName</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='error_chain/struct.Backtrace.html' title='error_chain::Backtrace'>Backtrace</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
